webseite_home:
    resource: "@WebseiteHomeBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /
    # {_locale}
    # requirements:
    #     _locale: fr|en|de|nl
    # defaults: { _locale: fr }

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"
